### ISSUE TITLE
Started with some script support anyway

### ISSUE THREAD

**Issue by AndersBillLinden** [SimpleBrowserDotNet/SimpleBrowser.WebDriver#29]
I have created a branch in SimpleBrowser and in SimpleBrowser.WebDriver both called "js". In SimpleBrowser, I had to expose the click event so I could use it in SimpleBrowser.WebDriver. Well, I have seen that Browser.cs contains some event handlers so I added one. Most changes are in SimpleBrowser.WebDriver.

As I understand it, you guys thinks it is a beast to include scripting in your project(s). I understand if you think so. On the other hand, if there is no javascript support, the test environment is very limited. In the long run people would perhaps expect scripting support. Without scripting, SimpleBrowser webdriver is also not sufficient for my own purposes.

The script support is still very rudimentary, but there is support for window.alert, console.log, document.createElement, body.onload, click events etc. The unit test cases should serve as a list of what is supported. The script engine I have used is ClearScript. There is still some work to do to get a decent DOM, but it is extremely easy to extend it. The goal will not be to imitate a full browser in a near future, but to be able to perform testing on websites. The reason I take interest in theese projects is that I have created a lot of webpages that needs test harnesses.

No handling of css has (yet) been added.

There is a test framework called phantomJS, but I did not like is a lot. It seems to have two modes, one where you have access to your own variables, nothing else and one where you run in a sandbox, and all you have access to is the script of the webpage you are testing, not your variables. So although you write tests in a scripting language, your options are less flexible and it felt a bit clumsy.

If you guys are interested in sooner or later adding my code to your project(s), maybe you think adding scripting is not that dramatic after all, maybe you also think it is a good idea to merge SimpleBrowser and SimpleBrowser.WebDriver? let me know. If you think the burden will be too high, the support mails too many etc, then let me know if I am free to create an offspring of your project(s). I would of course prefer to cooperate with you.

**Comment by Teun** [comment]
Would still be awesome, but I still don't expect this to be feasible. Now closing this 4 year old issue.
