### ISSUE TITLE
How to upload a image

### ISSUE THREAD

**Issue by arungopalam** [SimpleBrowserDotNet/SimpleBrowser.WebDriver#30]
I keep getting error
System.ArgumentException: The path is not of a legal form.

**Comment by kevingy** [comment]
Hello @arungopalam,

This thread is from more than two years ago. Did you resolve this issue? Do you still need assistance?

Kevin

**Comment by arungopalam** [comment]
Haha

No I don't need now
I am not screen scrapping

Regards
